require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThermostatsController do

  before(:each) do
    Location.new do |l|
      l.address = '123 Main St, Some Town, USA'
    end.save!
  end

  # This should return the minimal set of attributes required to create a valid
  # Thermostat. As you add validations to Thermostat, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { location_id: Location.first.id, serial_number: 12345, set_point: 80  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThermostatsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all thermostats as @thermostats" do
      thermostat = Thermostat.create! valid_attributes
      get :index, {}, valid_session
      assigns(:thermostats).should eq([thermostat])
    end
  end

  describe "GET show" do
    it "assigns the requested thermostat as @thermostat" do
      thermostat = Thermostat.create! valid_attributes
      get :show, {:id => thermostat.to_param}, valid_session
      assigns(:thermostat).should eq(thermostat)
    end
  end

  describe "GET new" do
    it "assigns a new thermostat as @thermostat" do
      get :new, {}, valid_session
      assigns(:thermostat).should be_a_new(Thermostat)
    end
  end

  describe "GET edit" do
    it "assigns the requested thermostat as @thermostat" do
      thermostat = Thermostat.create! valid_attributes
      get :edit, {:id => thermostat.to_param}, valid_session
      assigns(:thermostat).should eq(thermostat)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Thermostat" do
        expect {
          post :create, {:thermostat => valid_attributes}, valid_session
        }.to change(Thermostat, :count).by(1)
      end

      it "assigns a newly created thermostat as @thermostat" do
        post :create, {:thermostat => valid_attributes}, valid_session
        assigns(:thermostat).should be_a(Thermostat)
        assigns(:thermostat).should be_persisted
      end

      it "redirects to the created thermostat" do
        post :create, {:thermostat => valid_attributes}, valid_session
        response.should redirect_to(Thermostat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved thermostat as @thermostat" do
        # Trigger the behavior that occurs when invalid params are submitted
        Thermostat.any_instance.stub(:save).and_return(false)
        post :create, {:thermostat => {  }}, valid_session
        assigns(:thermostat).should be_a_new(Thermostat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Thermostat.any_instance.stub(:save).and_return(false)
        post :create, {:thermostat => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested thermostat" do
        thermostat = Thermostat.create! valid_attributes
        # Assuming there are no other thermostats in the database, this
        # specifies that the Thermostat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Thermostat.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => thermostat.to_param, :thermostat => { "these" => "params" }}, valid_session
      end

      it "assigns the requested thermostat as @thermostat" do
        thermostat = Thermostat.create! valid_attributes
        put :update, {:id => thermostat.to_param, :thermostat => valid_attributes}, valid_session
        assigns(:thermostat).should eq(thermostat)
      end

      it "redirects to the thermostat" do
        thermostat = Thermostat.create! valid_attributes
        put :update, {:id => thermostat.to_param, :thermostat => valid_attributes}, valid_session
        response.should redirect_to(thermostat)
      end
    end

    describe "with invalid params" do
      it "assigns the thermostat as @thermostat" do
        thermostat = Thermostat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Thermostat.any_instance.stub(:save).and_return(false)
        put :update, {:id => thermostat.to_param, :thermostat => {  }}, valid_session
        assigns(:thermostat).should eq(thermostat)
      end

      it "re-renders the 'edit' template" do
        thermostat = Thermostat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Thermostat.any_instance.stub(:save).and_return(false)
        put :update, {:id => thermostat.to_param, :thermostat => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested thermostat" do
      thermostat = Thermostat.create! valid_attributes
      expect {
        delete :destroy, {:id => thermostat.to_param}, valid_session
      }.to change(Thermostat, :count).by(-1)
    end

    it "redirects to the thermostats list" do
      thermostat = Thermostat.create! valid_attributes
      delete :destroy, {:id => thermostat.to_param}, valid_session
      response.should redirect_to(thermostats_url)
    end
  end

end
